### PR TITLE
Criar instancia

### PR DESCRIPTION
**Pull request by diogomarcondes85**

### CODE REVIEW

**Comment by diogomarcondes85** [comment]
atlantis plan

**Comment by diogomarcondes85** [comment]
atlantis plan

**Comment by diogomarcondes85** [comment]
atlantis plan

**Comment by diogomarcondes85** [comment]
Ran Plan for dir: `.` workspace: `default`

**Plan Error**
<details><summary>Show Output</summary>

```
running "/bin/terraform init -input=false -upgrade" in "/root/.atlantis/repos/diogomarcondes85/sistema1/2/default": exit status 1

Initializing the backend...
╷
│ Error: error configuring S3 Backend: no valid credential sources for S3 Backend found.
│ 
│ Please see https://www.terraform.io/docs/language/settings/backends/s3.html
│ for more information about providing credentials.
│ 
│ Error: NoCredentialProviders: no valid providers in chain. Deprecated.
│ 	For verbose messaging see aws.Config.CredentialsChainVerboseErrors
│ 
│ 
│ 
╵


```
</details>

**Comment by diogomarcondes85** [comment]
atlantis plan

**Comment by diogomarcondes85** [comment]
Ran Plan for dir: `.` workspace: `default`

**Plan Error**
<details><summary>Show Output</summary>

```
running "/bin/terraform init -input=false -upgrade" in "/root/.atlantis/repos/diogomarcondes85/sistema1/2/default": exit status 1

Initializing the backend...
╷
│ Error: error configuring S3 Backend: no valid credential sources for S3 Backend found.
│ 
│ Please see https://www.terraform.io/docs/language/settings/backends/s3.html
│ for more information about providing credentials.
│ 
│ Error: NoCredentialProviders: no valid providers in chain. Deprecated.
│ 	For verbose messaging see aws.Config.CredentialsChainVerboseErrors
│ 
│ 
│ 
╵


```
</details>

**Comment by diogomarcondes85** [comment]
atlantis plan

**Comment by diogomarcondes85** [comment]
Ran Plan for dir: `.` workspace: `default`

**Plan Error**
<details><summary>Show Output</summary>

```
running "/bin/terraform init -input=false -upgrade" in "/root/.atlantis/repos/diogomarcondes85/sistema1/2/default": exit status 1

Initializing the backend...
╷
│ Error: error configuring S3 Backend: no valid credential sources for S3 Backend found.
│ 
│ Please see https://www.terraform.io/docs/language/settings/backends/s3.html
│ for more information about providing credentials.
│ 
│ Error: NoCredentialProviders: no valid providers in chain. Deprecated.
│ 	For verbose messaging see aws.Config.CredentialsChainVerboseErrors
│ 
│ 
│ 
╵


```
</details>

**Comment by diogomarcondes85** [comment]
atlantis plan

**Comment by diogomarcondes85** [comment]
Ran Plan for dir: `.` workspace: `default`

**Plan Error**
<details><summary>Show Output</summary>

```
running "/bin/terraform init -input=false -upgrade" in "/root/.atlantis/repos/diogomarcondes85/sistema1/2/default": exit status 1

Initializing the backend...
╷
│ Error: error configuring S3 Backend: no valid credential sources for S3 Backend found.
│ 
│ Please see https://www.terraform.io/docs/language/settings/backends/s3.html
│ for more information about providing credentials.
│ 
│ Error: NoCredentialProviders: no valid providers in chain. Deprecated.
│ 	For verbose messaging see aws.Config.CredentialsChainVerboseErrors
│ 
│ 
│ 
╵


```
</details>

**Comment by diogomarcondes85** [comment]
atlantis plan

**Comment by diogomarcondes85** [comment]
Ran Plan for dir: `.` workspace: `default`

**Plan Error**
<details><summary>Show Output</summary>

```
running "/bin/terraform init -input=false -upgrade" in "/root/.atlantis/repos/diogomarcondes85/sistema1/2/default": exit status 1

Initializing the backend...
╷
│ Error: error configuring S3 Backend: no valid credential sources for S3 Backend found.
│ 
│ Please see https://www.terraform.io/docs/language/settings/backends/s3.html
│ for more information about providing credentials.
│ 
│ Error: NoCredentialProviders: no valid providers in chain. Deprecated.
│ 	For verbose messaging see aws.Config.CredentialsChainVerboseErrors
│ 
│ 
│ 
╵


```
</details>

**Comment by diogomarcondes85** [comment]
atlantis plan

**Comment by diogomarcondes85** [comment]
Ran Plan for dir: `.` workspace: `default`

**Plan Error**
```
running "/bin/terraform plan -input=false -refresh -out \"/root/.atlantis/repos/diogomarcondes85/sistema1/2/default/default.tfplan\"" in "/root/.atlantis/repos/diogomarcondes85/sistema1/2/default": exit status 1
╷
│ Error: configuring Terraform AWS Provider: failed to get shared config profile, default
│ 
│   with provider["registry.terraform.io/hashicorp/aws"],
│   on provider.tf line 1, in provider "aws":
│    1: provider "aws" {
│ 
╵

```

**Comment by diogomarcondes85** [comment]
atlantis plan

**Comment by diogomarcondes85** [comment]
Ran Plan for dir: `.` workspace: `default`

**Plan Error**
<details><summary>Show Output</summary>

```
running "/bin/terraform plan -input=false -refresh -out \"/root/.atlantis/repos/diogomarcondes85/sistema1/2/default/default.tfplan\"" in "/root/.atlantis/repos/diogomarcondes85/sistema1/2/default": exit status 1
╷
│ Error: configuring Terraform AWS Provider: IAM Role (arn:aws:iam::699094709586:role/Github) cannot be assumed.
│ 
│ There are a number of possible causes of this - the most common are:
│   * The credentials used in order to assume the role are invalid
│   * The credentials do not have appropriate permission to assume the role
│   * The role ARN is not valid
│ 
│ Error: operation error STS: AssumeRole, https response error StatusCode: 403, RequestID: 510cd5da-a8ed-4c22-ad2d-c1bc449f1783, api error AccessDenied: User: arn:aws:sts::699094709586:assumed-role/diogo/i-0a8633b5cdc0628b8 is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam::699094709586:role/Github
│ 
│ 
│   with provider["registry.terraform.io/hashicorp/aws"],
│   on provider.tf line 1, in provider "aws":
│    1: provider "aws" {
│ 
╵

```
</details>

**Comment by diogomarcondes85** [comment]
atlantis plan

**Comment by diogomarcondes85** [comment]
Ran Plan for dir: `.` workspace: `default`

<details><summary>Show Output</summary>

```diff
data.aws_ami.ubuntu: Reading...
data.aws_ami.ubuntu: Read complete after 0s [id=ami-09cd747c78a9add63]

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
+ create

Terraform will perform the following actions:

  # aws_instance.terraform-1 will be created
+ resource "aws_instance" "terraform-1" {
      + ami                                  = "ami-09cd747c78a9add63"
      + arn                                  = (known after apply)
      + associate_public_ip_address          = true
      + availability_zone                    = (known after apply)
      + cpu_core_count                       = (known after apply)
      + cpu_threads_per_core                 = (known after apply)
      + disable_api_stop                     = (known after apply)
      + disable_api_termination              = (known after apply)
      + ebs_optimized                        = (known after apply)
      + get_password_data                    = false
      + host_id                              = (known after apply)
      + host_resource_group_arn              = (known after apply)
      + iam_instance_profile                 = (known after apply)
      + id                                   = (known after apply)
      + instance_initiated_shutdown_behavior = (known after apply)
      + instance_state                       = (known after apply)
      + instance_type                        = "t2.micro"
      + ipv6_address_count                   = (known after apply)
      + ipv6_addresses                       = (known after apply)
      + key_name                             = "diogo"
      + monitoring                           = (known after apply)
      + outpost_arn                          = (known after apply)
      + password_data                        = (known after apply)
      + placement_group                      = (known after apply)
      + placement_partition_number           = (known after apply)
      + primary_network_interface_id         = (known after apply)
      + private_dns                          = (known after apply)
      + private_ip                           = (known after apply)
      + public_dns                           = (known after apply)
      + public_ip                            = (known after apply)
      + secondary_private_ips                = (known after apply)
      + security_groups                      = (known after apply)
      + source_dest_check                    = true
      + subnet_id                            = "subnet-0b46358b7f41a0ce5"
      + tags                                 = {
          + "Name" = "Terraform-01"
        }
      + tags_all                             = {
          + "Name" = "Terraform-01"
        }
      + tenancy                              = (known after apply)
      + user_data                            = (known after apply)
      + user_data_base64                     = (known after apply)
      + user_data_replace_on_change          = false
      + vpc_security_group_ids               = (known after apply)

      + capacity_reservation_specification {
          + capacity_reservation_preference = (known after apply)

          + capacity_reservation_target {
              + capacity_reservation_id                 = (known after apply)
              + capacity_reservation_resource_group_arn = (known after apply)
            }
        }

      + ebs_block_device {
          + delete_on_termination = (known after apply)
          + device_name           = (known after apply)
          + encrypted             = (known after apply)
          + iops                  = (known after apply)
          + kms_key_id            = (known after apply)
          + snapshot_id           = (known after apply)
          + tags                  = (known after apply)
          + throughput            = (known after apply)
          + volume_id             = (known after apply)
          + volume_size           = (known after apply)
          + volume_type           = (known after apply)
        }

      + enclave_options {
          + enabled = (known after apply)
        }

      + ephemeral_block_device {
          + device_name  = (known after apply)
          + no_device    = (known after apply)
          + virtual_name = (known after apply)
        }

      + maintenance_options {
          + auto_recovery = (known after apply)
        }

      + metadata_options {
          + http_endpoint               = (known after apply)
          + http_put_response_hop_limit = (known after apply)
          + http_tokens                 = (known after apply)
          + instance_metadata_tags      = (known after apply)
        }

      + network_interface {
          + delete_on_termination = (known after apply)
          + device_index          = (known after apply)
          + network_card_index    = (known after apply)
          + network_interface_id  = (known after apply)
        }

      + private_dns_name_options {
          + enable_resource_name_dns_a_record    = (known after apply)
          + enable_resource_name_dns_aaaa_record = (known after apply)
          + hostname_type                        = (known after apply)
        }

      + root_block_device {
          + delete_on_termination = (known after apply)
          + device_name           = (known after apply)
          + encrypted             = (known after apply)
          + iops                  = (known after apply)
          + kms_key_id            = (known after apply)
          + tags                  = (known after apply)
          + throughput            = (known after apply)
          + volume_id             = (known after apply)
          + volume_size           = (known after apply)
          + volume_type           = (known after apply)
        }
    }

  # aws_instance.terraform-2 will be created
+ resource "aws_instance" "terraform-2" {
      + ami                                  = "ami-09cd747c78a9add63"
      + arn                                  = (known after apply)
      + associate_public_ip_address          = true
      + availability_zone                    = (known after apply)
      + cpu_core_count                       = (known after apply)
      + cpu_threads_per_core                 = (known after apply)
      + disable_api_stop                     = (known after apply)
      + disable_api_termination              = (known after apply)
      + ebs_optimized                        = (known after apply)
      + get_password_data                    = false
      + host_id                              = (known after apply)
      + host_resource_group_arn              = (known after apply)
      + iam_instance_profile                 = (known after apply)
      + id                                   = (known after apply)
      + instance_initiated_shutdown_behavior = (known after apply)
      + instance_state                       = (known after apply)
      + instance_type                        = "t2.micro"
      + ipv6_address_count                   = (known after apply)
      + ipv6_addresses                       = (known after apply)
      + key_name                             = "diogo"
      + monitoring                           = (known after apply)
      + outpost_arn                          = (known after apply)
      + password_data                        = (known after apply)
      + placement_group                      = (known after apply)
      + placement_partition_number           = (known after apply)
      + primary_network_interface_id         = (known after apply)
      + private_dns                          = (known after apply)
      + private_ip                           = (known after apply)
      + public_dns                           = (known after apply)
      + public_ip                            = (known after apply)
      + secondary_private_ips                = (known after apply)
      + security_groups                      = (known after apply)
      + source_dest_check                    = true
      + subnet_id                            = "subnet-0b46358b7f41a0ce5"
      + tags                                 = {
          + "Name" = "Terraform-02"
        }
      + tags_all                             = {
          + "Name" = "Terraform-02"
        }
      + tenancy                              = (known after apply)
      + user_data                            = (known after apply)
      + user_data_base64                     = (known after apply)
      + user_data_replace_on_change          = false
      + vpc_security_group_ids               = (known after apply)

      + capacity_reservation_specification {
          + capacity_reservation_preference = (known after apply)

          + capacity_reservation_target {
              + capacity_reservation_id                 = (known after apply)
              + capacity_reservation_resource_group_arn = (known after apply)
            }
        }

      + ebs_block_device {
          + delete_on_termination = (known after apply)
          + device_name           = (known after apply)
          + encrypted             = (known after apply)
          + iops                  = (known after apply)
          + kms_key_id            = (known after apply)
          + snapshot_id           = (known after apply)
          + tags                  = (known after apply)
          + throughput            = (known after apply)
          + volume_id             = (known after apply)
          + volume_size           = (known after apply)
          + volume_type           = (known after apply)
        }

      + enclave_options {
          + enabled = (known after apply)
        }

      + ephemeral_block_device {
          + device_name  = (known after apply)
          + no_device    = (known after apply)
          + virtual_name = (known after apply)
        }

      + maintenance_options {
          + auto_recovery = (known after apply)
        }

      + metadata_options {
          + http_endpoint               = (known after apply)
          + http_put_response_hop_limit = (known after apply)
          + http_tokens                 = (known after apply)
          + instance_metadata_tags      = (known after apply)
        }

      + network_interface {
          + delete_on_termination = (known after apply)
          + device_index          = (known after apply)
          + network_card_index    = (known after apply)
          + network_interface_id  = (known after apply)
        }

      + private_dns_name_options {
          + enable_resource_name_dns_a_record    = (known after apply)
          + enable_resource_name_dns_aaaa_record = (known after apply)
          + hostname_type                        = (known after apply)
        }

      + root_block_device {
          + delete_on_termination = (known after apply)
          + device_name           = (known after apply)
          + encrypted             = (known after apply)
          + iops                  = (known after apply)
          + kms_key_id            = (known after apply)
          + tags                  = (known after apply)
          + throughput            = (known after apply)
          + volume_id             = (known after apply)
          + volume_size           = (known after apply)
          + volume_type           = (known after apply)
        }
    }

  # aws_security_group.permitir_ssh_http will be created
+ resource "aws_security_group" "permitir_ssh_http" {
      + arn                    = (known after apply)
      + description            = "Permite SSH e HTTP na instancia EC2"
      + egress                 = [
          + {
              + cidr_blocks      = [
                  + "0.0.0.0/0",
                ]
              + description      = ""
              + from_port        = 0
              + ipv6_cidr_blocks = []
              + prefix_list_ids  = []
              + protocol         = "-1"
              + security_groups  = []
              + self             = false
              + to_port          = 0
            },
        ]
      + id                     = (known after apply)
      + ingress                = [
          + {
              + cidr_blocks      = [
                  + "0.0.0.0/0",
                ]
              + description      = "HTTP to EC2"
              + from_port        = 80
              + ipv6_cidr_blocks = []
              + prefix_list_ids  = []
              + protocol         = "tcp"
              + security_groups  = []
              + self             = false
              + to_port          = 80
            },
          + {
              + cidr_blocks      = [
                  + "0.0.0.0/0",
                ]
              + description      = "SSH to EC2"
              + from_port        = 22
              + ipv6_cidr_blocks = []
              + prefix_list_ids  = []
              + protocol         = "tcp"
              + security_groups  = []
              + self             = false
              + to_port          = 22
            },
        ]
      + name                   = "permitir_ssh"
      + name_prefix            = (known after apply)
      + owner_id               = (known after apply)
      + revoke_rules_on_delete = false
      + tags                   = {
          + "Name" = "permitir_ssh_e_http"
        }
      + tags_all               = {
          + "Name" = "permitir_ssh_e_http"
        }
      + vpc_id                 = "vpc-0303fb420f519ea05"
    }

Plan: 3 to add, 0 to change, 0 to destroy.
```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d .`
* :put_litter_in_its_place: To **delete** this plan click [here](http://ip-172-31-88-56.ec2.internal:4141/lock?id=diogomarcondes85%252Fsistema1%252F.%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d .`
</details>
Plan: 3 to add, 0 to change, 0 to destroy.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Review by RenatoFilizola — APPROVED** [review]
- Arquivos checados e aprovados.

**Review by diogomarcondes85 — COMMENTED** [review]
Obrigado

**Review by RenatoFilizola — APPROVED** [review]

**Review by RenatoFilizola — APPROVED** [review]

**Review by RenatoFilizola — APPROVED** [review]

**Review by RenatoFilizola — APPROVED** [review]

**Review by RenatoFilizola — CHANGES_REQUESTED** [review]
Verificar provider.tf

**Review by diogomarcondes85 — COMMENTED** [review]
Mudado

**Review by RenatoFilizola — APPROVED** [review]

**Review by vongrossi — APPROVED** [review]

**Review by vongrossi — APPROVED** [review]
Revisado

**Review by vongrossi — APPROVED** [review]
Revisado

**Comment by diogomarcondes85** [comment]
atlantis apply

**Comment by diogomarcondes85** [comment]
```
Error: This repo is not allowlisted for Atlantis.
```

**Comment by diogomarcondes85** [comment]
atlantis apply

**Comment by diogomarcondes85** [comment]
**Apply Error**
```
stat /root/.atlantis/repos/ddmarcondes/sistema1/2: no such file or directory
```

**Comment by diogomarcondes85** [comment]
atlantis apply

**Comment by diogomarcondes85** [comment]
Ran Apply for dir: `.` workspace: `default`

<details><summary>Show Output</summary>

```diff
aws_security_group.permitir_ssh_http: Creating...
aws_security_group.permitir_ssh_http: Creation complete after 3s [id=sg-031865ebdc546a961]
aws_instance.terraform-2: Creating...
aws_instance.terraform-1: Creating...
aws_instance.terraform-2: Still creating... [10s elapsed]
aws_instance.terraform-1: Still creating... [10s elapsed]
aws_instance.terraform-2: Still creating... [20s elapsed]
aws_instance.terraform-1: Still creating... [20s elapsed]
aws_instance.terraform-2: Still creating... [30s elapsed]
aws_instance.terraform-1: Still creating... [30s elapsed]
aws_instance.terraform-1: Creation complete after 32s [id=i-0807dc5c07e6ccc93]
aws_instance.terraform-2: Still creating... [40s elapsed]
aws_instance.terraform-2: Creation complete after 42s [id=i-04a208f3d4f93ccfa]

Apply complete! Resources: 3 added, 0 changed, 0 destroyed.
```

</details>

**Comment by diogomarcondes85** [comment]
atlantis destroy

**Comment by diogomarcondes85** [comment]
```
Error: unknown command "destroy".
Run 'atlantis --help' for usage.
Available commands(--allow-commands): version, plan, apply, unlock, approve_policies
```

**Pull request merged**
